import assert from"node:assert/strict";import{readFile,access}from"node:fs/promises";import test from"node:test";const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("公开页面统一使用 D1 仓库",async()=>{const sources=await Promise.all([read("app/page.tsx"),read("app/archive/page.tsx"),read("app/item/[slug]/page.tsx")]);for(const source of sources){assert.match(source,/Resource|listResources|findResource/);assert.doesNotMatch(source,/lib\/resources/)}});
test("所有管理页面执行唯一管理员校验",async()=>{for(const file of["app/admin/page.tsx","app/admin/upload/page.tsx","app/admin/edit/[id]/page.tsx"]){const source=await read(file);assert.match(source,/requireLeemingAdmin/);assert.match(source,/force-dynamic/)}});
test("所有写入接口执行唯一管理员校验",async()=>{for(const file of["app/api/resources/route.ts","app/api/resources/[id]/route.ts","app/api/files/route.ts","app/api/files/[...key]/route.ts"])assert.match(await read(file),/getLeemingAdmin/)});
test("D1 与 R2 部署声明和迁移齐全",async()=>{const hosting=JSON.parse(await read(".openai/hosting.json"));assert.equal(hosting.d1,"DB");assert.equal(hosting.r2,"ARCHIVE");await Promise.all([access(new URL("../drizzle/0000_opposite_alice.sql",import.meta.url)),access(new URL("../drizzle/0002_add_object_key.sql",import.meta.url))])});

test("admin pages use LEEMING password session instead of ChatGPT login",async()=>{const source=await read("app/admin-auth.ts");assert.match(source,/ADMIN_SESSION_COOKIE/);assert.match(source,/adminLoginPath/);assert.doesNotMatch(source,/chatGPTSignInPath|signin-with-chatgpt|getChatGPTUser/)});
test("public navigation does not expose admin login",async()=>{const source=await read("components/site-nav.tsx");assert.doesNotMatch(source,/href:"\/admin"/);assert.doesNotMatch(source,/label:"Admin"/)});
test("resource tutorials are persisted and rendered as optional item content",async()=>{assert.match(await read("db/schema.ts"),/tutorial/);await access(new URL("../drizzle/0003_add_tutorial.sql",import.meta.url));assert.match(await read("app/item/[slug]/page.tsx"),/tutorial-section/);assert.match(await read("components/tutorial-editor.tsx"),/添加步骤/);assert.match(await read("components/tutorial-editor.tsx"),/api\/files/)});
test("legacy ChatGPT auth helper has been removed",async()=>{await assert.rejects(()=>access(new URL("../app/chatgpt-auth.ts",import.meta.url)))});
